
# Node docker image on which this would be run
image: node:latest

#This command is run before actual stages start running
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - npm install

stages:
  - test
  - deploy

lint:
  stage: test
  script:
    - npm run lint

deployToAWS:
  only:
    - master
  stage: deploy
  script:
    - bash deploy.sh